syntax on
syntax enable

set mouse=a
set wrap

set number

" lets Y yank to end of line
nnoremap Y y$

" remap esc to jk
inoremap jk <Esc>

" reload file if it changes on disk
set autoread

" pretty highlighting on yank
augroup highlight_yank
    autocmd!
    au TextYankPost * silent! lua vim.highlight.on_yank{higroup="IncSearch", timeout=700}
augroup END

